<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\LeanOptionsLab\Domain\**\*.cs" Link="Domain\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
